import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  const onOnClicked = async (e) => {
    e.preventDefault()
    const response = await fetch('/api/hello', {
      method: 'POST',
      body: JSON.stringify({ led: "ON" }),
      headers: { 'Content-Type': 'application/json' }
    })
  }
  const onOffClicked = async (e) => {
    console.log("OFFFF")
    e.preventDefault()
    const response = await fetch('/api/hello', {
      method: 'POST',
      body: JSON.stringify({ led: "OFF" }),
      headers: { 'Content-Type': 'application/json' }
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button type="button" onClick={onOnClicked}>
          ON
        </button>
        <button type="button" onClick={onOffClicked}>
          OFF
        </button> 
      </main>


    </div>
  )
}
